server:
  port: 8080
spring:
  application:
    name: bp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bamboo_paper?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  type-aliases-package: com.liersan.bp.entity
  configuration:
    map-underscore-to-camel-case: true
mapper:
  wrap-keyword: "`{0}`"
logging:
  level:
    com.liersan: debug
